# Generated by Django 5.1.7 on 2025-04-02 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Material_Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVENTPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVENQTY', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('INVENCOD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Material_Master.mmprodpt')),
            ],
        ),
    ]
