# Generated by Django 5.1.7 on 2025-04-07 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCMATER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCACODE', models.CharField(max_length=4, unique=True)),
                ('LOCANAME', models.CharField(max_length=50)),
                ('LOCDESCR', models.TextField(blank=True, null=True)),
                ('LOCCAPAC', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='inventpt',
            name='INVENLOC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouse.locmater'),
        ),
    ]
