# Generated by Django 5.1.7 on 2025-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0002_locmater_inventpt_invenloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventpt',
            name='INVENLOT',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
