# Generated by Django 5.1.7 on 2025-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0003_inventpt_invenlot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventpt',
            name='INVENLOT',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
    ]
