# Generated by Django 5.1.7 on 2025-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMPRODPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMPROCDE', models.CharField(editable=False, max_length=14, unique=True)),
                ('MMPRODES', models.CharField(max_length=40)),
                ('MMPROPRE', models.CharField(max_length=10)),
                ('MMPROSTA', models.BooleanField(default=True)),
                ('MMPRODAT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
